return {
  "nvim-telescope/telescope.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  config = function()
    require("telescope").setup({
      defaults = {
        layout_strategy = "bottom_pane",
        layout_config = { height = 0.7, prompt_position = "top", preview_width = 0.45 },
        sorting_strategy = "ascending",
        winblend = 0,
        border = true,
        previewer = true,
        path_display = { "truncate" },

        file_ignore_patterns = {
          -- Media
          "%.png$",
          "%.jpg$",
          "%.jpeg$",
          "%.tga$",
          "%.gif$",
          "%.bmp$",
          "%.tiff$",
          "%.psd$",
          "%.mp3$",
          "%.wav$",
          "%.ogg$",
          "%.mp4$",
          "%.mov$",
          "%.avi$",
          "%.fbx$",
          "%.obj$",
          "%.blend$",
          "%.dae$",
          "%.3ds$",
          "%.dxf$",
          "%.stl$",
          "%.ply$",
          "%.gltf$",
          "%.glb$",
          "%.max$",
          "%.c4d$",
          "%.mb$",
          "%.ma$",

          -- Unity-specific binary
          "%.asset$",
          "%.meta$",
          "%.prefab$",
          "%.unitypackage$",
          "%.unity$",
          "%.mat$",
          "%.cubemap$",
          "%.physicMaterial$",

          -- Unity project-generated folders
          "^Library/",
          "^Temp/",
          "^Obj/",
          "^obj/",
          "^Build/",
          "^Builds/",
          "^Logs/",
          "^UserSettings/",
          "^MemoryCaptures/",
          "^CrashReports/",

          -- IDE/editor junk
          "%.csproj$",
          "%.sln$",
          "%.pidb$",
          "%.user$",
          "%.booproj$",
          "^.vs/",
          "^.idea/",
          "^.vscode/",
        },
      },
    })
  end,
}
